export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  COUNTRY_NOT_FOUND = 'COUNTRY_NOT_FOUND',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  INVALID_TAX_REGIME = 'INVALID_TAX_REGIME',
  INVALID_CTC = 'INVALID_CTC',
  NO_ACTIVE_RULES = 'NO_ACTIVE_RULES',
  UNSUPPORTED_CURRENCY = 'UNSUPPORTED_CURRENCY',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
